[tool.poetry]
name = "wagtail_tenants"
version = "0.1.0"
description = "Adds multitenancy to wagtail cms"
authors = ["Boris Brue <boris@zuckersalzundpfeffer.de>"]

[tool.poetry.dependencies]
python = "^3.6.2"
django-tenants = "^3.3.4"
sphinx = {version = "^3", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.11b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["sphinx"]