[tool.poetry]
name = "wagtail_tenants"
version = "0.1.2"
description = "Adds multitenancy based on django_tenants to wagtail cms"
authors = ["Boris Brue <boris@zuckersalzundpfeffer.de>"]

[tool.poetry.dependencies]
python = "^3.6.2"
django-tenants = "^3.3.4"
myst-parser = "^0.15.2"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
flake8 = "^4.0.1"
sphinx = {version = "^3", optional = true}
wagtail = "^2.15.1"
isort = "^5.10.1"
flake8-black = "^0.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["sphinx"]